### ISSUE TITLE
how to run for subpath event a full domain

### ISSUE THREAD

**Issue by mckaygerhard** [ViBiOh/vith#51]
i can see in usage the  hicjacking of the root only

but i can see also `-address` and `--url` options.. 

those options can be combined with a reverse proxy to server in a subpath? 
by example no DNS provided ip only path? for `192.168.1.10` ?

**Comment by ViBiOh** [comment]
`-address` option is to defined listening address. If blank, it listens on all interfaces `*:1080`.

`-url` is the address use for running an healthcheck. Docker images are from scratch, so there is not `curl` or `wget` inside image for running HEALTHCHECK command. I add a simple feature in the binary for having a way to perform a GET request. If `-url` is defined, the binary make a GET request and exit.

You can configure your reverse proxy for stripping prefix of subpath if you want. `vith` is a very simple binary. It takes a video payload and returns the thumbnail of it, no big deal.

**Comment by mckaygerhard** [comment]
yes .. discovered about the listen (i was confused, sorry), ok, this is not so necesary in the case of video cache i m thinking in closing this but i will let open for future references, due i m so busy, but if i can i could provide in future a pull request with some piece of code.. THANKS!
