### ISSUE TITLE
feat req: (sec) possibility to specify the thumb dir work

### ISSUE THREAD

**Issue by mckaygerhard** [ViBiOh/vith#52]
i check code and it seems all data is working in /tmp that is open in shared servers..

could be great if in future we can use command line to set that location, due there's no clear way to compiling without networking to distribute in close and intranet environments

**Comment by ViBiOh** [comment]
I put everything in `/tmp/` to be sure files will be deleted, even in case of failure. I can add an option for changing it sure.

**Comment by mckaygerhard** [comment]
thanks.. there 3 reasons for this:

1. we can set a special directory to this with special command to clean it! by example a SSD disk dedicated to!
2. most linuxes does not complain the /tmp location, so we can specify
3. by this way i can manage the storage and volume inside dockers also set a different container to catch videos without monitoring the traffic!
